apiVersion: v1
kind: Secret
metadata:
  name: hcbs-backend-secret
  namespace: hcbs
  labels:
    app: hcbs-backend
    component: api
    part-of: hcbs-revenue-management
  annotations:
    description: "Sensitive configuration for HCBS Revenue Management System Backend"
type: Opaque
data:
  # Database Credentials
  DB_USER: ${BASE64_DB_USER}
  DB_PASSWORD: ${BASE64_DB_PASSWORD}
  
  # Redis Credentials
  REDIS_PASSWORD: ${BASE64_REDIS_PASSWORD}
  
  # JWT Authentication
  JWT_SECRET: ${BASE64_JWT_SECRET}
  JWT_PRIVATE_KEY: ${BASE64_JWT_PRIVATE_KEY}
  JWT_PUBLIC_KEY: ${BASE64_JWT_PUBLIC_KEY}
  
  # Email Configuration
  SMTP_USER: ${BASE64_SMTP_USER}
  SMTP_PASSWORD: ${BASE64_SMTP_PASSWORD}
  
  # AWS Credentials
  AWS_ACCESS_KEY_ID: ${BASE64_AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${BASE64_AWS_SECRET_ACCESS_KEY}
  
  # Integration Credentials
  CLEARINGHOUSE_API_KEY: ${BASE64_CLEARINGHOUSE_API_KEY}
  CLEARINGHOUSE_API_SECRET: ${BASE64_CLEARINGHOUSE_API_SECRET}
  EHR_API_KEY: ${BASE64_EHR_API_KEY}
  EHR_API_SECRET: ${BASE64_EHR_API_SECRET}
  
  # Security Keys
  ENCRYPTION_KEY: ${BASE64_ENCRYPTION_KEY}
  MFA_SECRET_KEY: ${BASE64_MFA_SECRET_KEY}
  SESSION_SECRET: ${BASE64_SESSION_SECRET}
  COOKIE_SECRET: ${BASE64_COOKIE_SECRET}