version: '3.8'

services:
  # NGINX proxy for routing, SSL termination, and security
  hcbs-proxy:
    build:
      context: ..
      dockerfile: proxy/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - hcbs-web
      - hcbs-backend
    networks:
      - frontend
      - backend
    volumes:
      - ./proxy/ssl:/etc/nginx/ssl:ro
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health", "||", "exit", "1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

  # Next.js frontend application
  hcbs-web:
    build:
      context: ..
      dockerfile: web/Dockerfile
    volumes:
      - ../../src/web:/app:delegated
      - node_modules_web:/app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost/api
      - API_URL=http://hcbs-backend:3000
    networks:
      - backend
    depends_on:
      - hcbs-backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health", "||", "exit", "1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  # Node.js/Express backend API
  hcbs-backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    volumes:
      - ../../src/backend:/app:delegated
      - node_modules_backend:/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=hcbs-db
      - DB_PORT=5432
      - DB_NAME=hcbs_revenue
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=hcbs-redis
      - REDIS_PORT=6379
      - JWT_SECRET=development_jwt_secret
      - JWT_EXPIRES_IN=1d
      - REFRESH_TOKEN_EXPIRES_IN=7d
      - CORS_ORIGIN=http://localhost
    networks:
      - backend
      - database
    depends_on:
      - hcbs-db
      - hcbs-redis
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health/live", "||", "exit", "1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  # PostgreSQL database
  hcbs-db:
    image: postgres:15.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hcbs_revenue
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - database
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  # Redis cache
  hcbs-redis:
    image: redis:7.0-alpine
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - database
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  node_modules_web:
    driver: local
  node_modules_backend:
    driver: local

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  database:
    driver: bridge