apiVersion: v1
kind: ConfigMap
metadata:
  name: hcbs-web-config
  namespace: hcbs
  labels:
    app: hcbs-web
    component: frontend
    part-of: hcbs-revenue-management
  annotations:
    description: "Non-sensitive configuration for HCBS Revenue Management System Web Frontend"
data:
  NODE_ENV: "production"
  NEXT_PUBLIC_APP_NAME: "HCBS Revenue Management System"
  NEXT_PUBLIC_APP_VERSION: "1.0.0"
  NEXT_PUBLIC_API_BASE_URL: "http://hcbs-backend.hcbs.svc.cluster.local/api"
  NEXT_PUBLIC_API_TIMEOUT: "15000"
  NEXT_PUBLIC_ENVIRONMENT: "production"
  NEXT_PUBLIC_ENABLE_MOCK_API: "false"
  NEXT_PUBLIC_ENABLE_ANALYTICS: "true"
  NEXT_PUBLIC_ENABLE_FEATURE_FLAGS: "false"
  NEXT_PUBLIC_DEFAULT_LOCALE: "en-US"
  NEXT_PUBLIC_SUPPORTED_LOCALES: "en-US"
  NEXT_PUBLIC_ENABLE_MFA: "true"
  NEXT_PUBLIC_SESSION_TIMEOUT: "15"
  NEXT_PUBLIC_MAX_CONCURRENT_SESSIONS: "3"
  NEXT_PUBLIC_ENABLE_HIPAA_COMPLIANCE: "true"
  NEXTAUTH_URL: "https://app.thinkcaring.com"
  NEXT_PUBLIC_DEBUG: "false"
  NEXT_PUBLIC_SHOW_REDUX_DEVTOOLS: "false"
  NEXT_PUBLIC_CSP_CONNECT_SRC: "'self' https://*.thinkcaring.com http://hcbs-backend.hcbs.svc.cluster.local"
  PORT: "3000"
  ANALYZE: "false"
  HEALTH_CHECK_PATH: "/api/health"
  METRICS_PATH: "/metrics"
  METRICS_ENABLED: "true"