// This file is automatically generated by Next.js and should not be edited.
// It provides TypeScript type definitions for Next.js features and environment variables.
// The file is regenerated when the Next.js version changes.

/// <reference types="next" />
/// <reference types="next/types/global" />
/// <reference types="next/image-types/global" />

// Type definitions for environment variables
declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_APP_NAME: string;
    NEXT_PUBLIC_APP_VERSION: string;
    NEXT_PUBLIC_API_BASE_URL: string;
    NEXT_PUBLIC_APP_ENV: string;
    NEXT_PUBLIC_ENABLE_ANALYTICS: string;
    NEXT_PUBLIC_ENABLE_MOCK_API: string;
  }
}